### ISSUE TITLE
"Pre-Approval_Status" column returns error on Submit Job

### ISSUE THREAD

**Issue by elmoyapandr** [pandrlegazpi/PPIM#4]
Solution (maybe haha): rename column name without "-" dash symbol.

Error:
![image](https://user-images.githubusercontent.com/74574865/100689235-0aece700-33bf-11eb-910a-fed46f8a2914.png)

**Comment by justjosh01** [comment]
dash remove and it's already working, the error is gone

**Comment by elmoyapandr** [comment]
confirmed. thanks josh.

![image](https://user-images.githubusercontent.com/74574865/100701781-439ab980-33db-11eb-92d8-1132e6999864.png)
